language: java

dist: trusty

jdk:
     - openjdk8
     - openjdk11

arch:
     - amd64
     - ppc64le

before_install:
     - |
       if [[ "$TRAVIS_CPU_ARCH" = "ppc64le" ]]; then 
        mkdir -p /opt/maven;
        curl https://downloads.apache.org/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz|tar -xz --strip 1 -C /opt/maven;
        export MAVEN_HOME=/opt/maven
        export PATH=${MAVEN_HOME}/bin:${PATH}
       fi

script: 
     - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
